name: Test

on: [push]

jobs: 
    test-build:
        run-on: ubuntu-latest 

        steps:
        - name: Checkout
          uses: actions/Checkout2
        
        - name: lista
          run: |
            chmod +x script.sh
            ./script.sh