name: Test

on: [push]

jobs: 
    test-build:
        runs-on: ubuntu-latest 

        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        
        - name: lista
          run: ls -al
               chmod 755 script.sh
               ./script.sh